services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
